# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: l_hand
  joint_model_group_pose: todo_no_pose_selected
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - rh_WRJ2
    - rh_WRJ1
    - rh_FFJ4
    - rh_FFJ3
    - rh_FFJ2
    - rh_FFJ1
    - rh_LFJ5
    - rh_LFJ4
    - rh_LFJ3
    - rh_LFJ2
    - rh_LFJ1
    - rh_MFJ4
    - rh_MFJ3
    - rh_MFJ2
    - rh_MFJ1
    - rh_RFJ4
    - rh_RFJ3
    - rh_RFJ2
    - rh_RFJ1
    - rh_THJ5
    - rh_THJ4
    - rh_THJ3
    - rh_THJ2
    - rh_THJ1
    - lh_WRJ2
    - lh_WRJ1
    - lh_FFJ4
    - lh_FFJ3
    - lh_FFJ2
    - lh_FFJ1
    - lh_LFJ5
    - lh_LFJ4
    - lh_LFJ3
    - lh_LFJ2
    - lh_LFJ1
    - lh_MFJ4
    - lh_MFJ3
    - lh_MFJ2
    - lh_MFJ1
    - lh_RFJ4
    - lh_RFJ3
    - lh_RFJ2
    - lh_RFJ1
    - lh_THJ5
    - lh_THJ4
    - lh_THJ3
    - lh_THJ2
    - lh_THJ1
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []